### ISSUE TITLE
[Feature Request] Core for Wii?

### ISSUE THREAD

**Issue by Cee123** [libretro/beetle-lynx-libretro#31]
Hi there, just wondering why this core is not available on Retroarch for Wii.

**Comment by f21red** [comment]
I assume it works, so added here.
https://github.com/libretro/libretro-super/pull/1161

**Comment by negativeExponent** [comment]
@Cee123 core has been updated. I did found instances where core can crash when loading another game with the same core. Hopefully this is fix on this device as well.

You may want to test after this PR is merged and available for your device though: https://github.com/libretro/beetle-lynx-libretro/pull/36

**Comment by Cee123** [comment]
I tried the latest version of the core both on the official release as well as the nightly, and it seems to still be doing the same thing. It runs fantastic (and I am pleasantly surprised) but if you change the game then it just crashes. There may be a workaround if you close the core or even retroarch, and then try to load another game.

**Comment by negativeExponent** [comment]
on handhelds, its easy to know why it would crash, but tricky to catch since it cant be replicated without the same device. hope its not big-endian related. ill see what i can find unless someone else will find it first...

**Comment by negativeExponent** [comment]
a few time has passed and i cant seem to find direct cause of issue. if this is still troubling you, try to create a crash-dump and hope someone can figure out from that (i sadly don't know how to read and analyze crash dumps)

**Comment by negativeExponent** [comment]
> I tried the latest version of the core both on the official release as well as the nightly, and it seems to still be doing the same thing. It runs fantastic (and I am pleasantly surprised) but if you change the game then it just crashes. There may be a workaround if you close the core or even retroarch, and then try to load another game.

please retest with latest commit if there's still any memory leaks.

**Comment by LibretroAdmin** [comment]
Closing until we get any feedback here.
