### ISSUE TITLE
Atari - Lynx (Beetle Lynx) won't open my roms

### ISSUE THREAD

**Issue by edlink98** [libretro/beetle-lynx-libretro#40]
Atari - Lynx (Beetle Lynx) won't open my roms (Error loading content)

Atari - Lynx (Beetle Lynx) does not open my roms I get the message (Error loading content) when loading atari lynx roms in .lnx and .zip format, I don't know what to do, the video driver I use was GL and the VULKAN, I already restarted my retroarch and it remains the same, I also already put the original Bios that Retroarch asks for and even so it does not load the roms.

With the Atari - Lynx (Handy) if I load the roms, but I want to try the "Bettle Lynx", what could be happening? I use the latest versions of Retroarch as well as the core.

**Comment by ToniBC** [comment]
Yes, the same thing happens to me and other people, since the last update something happened that does not load the roms.

We have to wait for it to be repaired.

**Comment by negativeExponent** [comment]
anylone can show logs
