### ISSUE TITLE
Is there supposed to be screen tearing in this core?

### ISSUE THREAD

**Issue by BParks21** [libretro/beetle-lynx-libretro#60]
Every game I've tested exhibits screen tearing on both my 60hz monitors. Vsync is enabled. I never owned a Lynx so maybe this is how it looked? My the actual Lynx had screen tearing?

**Comment by negativeExponent** [comment]
Most, if not all of the games run at 75hz

**Comment by BParks21** [comment]
> Most, if not all of the games run at 75hz

Ahhh, so there's no way around it? What would be the best way to force this core to run at 75hz?
